import json
from elasticsearch import Elasticsearch
import pandas as pd

ES_HOST = "http://localhost:9200"
INDEX_NAME = "opennet_news"

es = Elasticsearch(ES_HOST)

def search(query, size=10):
    body = {
        "query": {
            "multi_match": {
                "query": query,
                "fields": ["title^2", "content", "keywords^3"]
            }
        }
    }
    res = es.search(index=INDEX_NAME, body=body, size=size)
    results = []
    for h in res.get("hits", {}).get("hits", []):
        results.append({
            "relevance": None,
            "id": h["_id"],
            "keywords": h["_source"].get("keywords", []),
            "title": h["_source"]["title"],
            "content": h["_source"]["content"]
        })
    return results

if __name__ == "__main__":
    queries = [
        "linux firewall",
"samba релиз",
"raid настройка",
"vpn сервер",
"zfs пул",
"ssh ключи",
"pam настройка",
"nginx защита",
"apache rewrite",
"audit журнал",
"cron задачи",
"nftables правила",
"iptables конфиг",
"selinux режим",
"strace запуск",
"namespaces примеры",
"cgroups настройка",
"bonding интерфейс",
"vlan tagging",
"openvpn настройка",
"wireguard параметры",
"samba ресурсы",
"mdadm raid",
"zfs создание",
"disk encryption",
"ssh hardening",
"rsync backup",
"backup стратегия",
"haproxy балансировка",
"nginx ddos",
"nginx proxy",
"windows firewall",
"dns windows",
"dhcp сервер",
"hyper-v виртуализация",
"powershell скрипт",
"smb безопасность",
"ntfs права",
"windows rds",
"exchange почта",
"azure connect",
"bitlocker шифрование",
"iis оптимизация",
"sql backup",
"wsl2 оптимизация",
"esxi гипервизор",
"cisco ios",
"mikrotik правила",
"pfsense vpn",
"opnsense firewall",
"uefi boot",
"bios обновление",
"tpm модуль",
"amd psp",
"nvme тестирование",
"ssd мониторинг",
"raspberry сервер",
"arduino проект",
"embedded linux",
"cross toolchain",
"ebpf трассировка",
"сокеты программирование",
"pthread пример",
"cuda программирование",
"fpga основы",
"verilog руководство",
"firmware тестирование",
"clean architecture",
"grpc сервис",
"swagger документация",
"git workflow",
"dockerfile оптимизация",
"code анализ",
"bash команды",
"ssh настройка",
"apt менеджер",
"cron автоматизация",
"sudo настройки",
"apparmor пример",
"dhcp linux",
"samba подключение",
"vsftpd конфиг",
"firewalld команда",
"ssl nginx",
"postfix конфигурация",
"wireguard пример",
"top процессы",
"tcpdump диагностика",
"iperf пример",
"grafana мониторинг",
"prometheus алерты",
"docker команды",
"kvm виртуализация",
"qemu настройка",
"ansible развертывание",
"kubernetes manifest",
"makefile пример",
"python скрипт",
"golang настройка",
"gdb отладка",
"git репозиторий",
"gitlab интеграция",
"pylint анализ",
"kernel panic анализ",
"linux dmesg ошибки",
"udev правила",
"systemd unit пример",
"grub rescue",
"grub2 настройка",
"fstab параметры",
"ext4 оптимизация",
"xfs настройка",
"btrfs snapshots",
"btrfs scrub",
"lvm thin provisioning",
"lvm snapshot",
"raid bbu проверка",
"smartctl тест",
"hdd ошибка pending",
"nvme прошивка",
"bluetooth linux",
"wifi драйвер rtl",
"intel microcode",
"amd microcode",
"i915 настройка",
"amdgpu проблемы",
"nouveau драйвер",
"nvidia dkms",
"mesa обновление",
"wayland проблемы",
"xorg конфиг",
"pipewire настройка",
"pulseaudio сбои",
"alsa mixer",
"linux irq балансировка",
"cgroups v2",
"systemd журнал",
"journald очистка",
"syslog анализ",
"auditd фильтры",
"selinux разрешить",
"apparmor профили",
"pam sudo правила",
"sudoers синтаксис",
"ssh fail2ban",
"fail2ban jail пример",
"iptables log",
"ipset пример",
"nftables migration",
"wireguard peers",
"openvpn client",
"strongswan туннель",
"ipsec конфигурация",
"bird routing",
"quagga ospf",
"frr routing",
"bgp communities",
"ospf cost",
"mpls basics",
"vxlan настройка",
"evpn пример",
"dhcp relay linux",
"dnsmasq настройки",
"bind9 acl",
"bind9 views",
"unbound dnssec",
"powerdns recursor",
"apache mpm event",
"nginx cache",
"nginx upstream",
"haproxy acl",
"haproxy stick-table",
"varnish vcl пример",
"squid proxy auth",
"postfix relayhost",
"postfix tls",
"dovecot ssl",
"imap сервер",
"exim маршрутизация",
"php-fpm параметры",
"perl cpan ошибки",
"python venv",
"pip зависимость",
"pipx установка",
"ruby rbenv",
"node pm2",
"npm rebuild",
"go cross compile",
"rust cargo оптимизация",
"java openjdk",
"jvm tuning",
"tomcat конфиг",
"wildfly deploy",
"kafka cluster",
"zookeeper настройка",
"rabbitmq очереди",
"redis persistence",
"redis sentinel",
"mongodb репликация",
"postgres vacuum",
"postgres indices",
"mysql query cache",
"mariadb репликация",
"sqlite wal",
"ceph osd",
"glusterfs volume",
"nfs проблема",
"samba winbind",
"iscsi target",
"multipath конфиг",
"openldap схема",
"ldap аутентификация",
"kerberos tickets",
"freeipa репликация",
"radius сервер",
"tacacs+ linux",
"snmpd конфиг",
"collectd плагины",
"prometheus exporters",
"grafana alerts",
"zabbix агент",
"icinga2 setup",
"elk ingest",
"filebeat конфиг",
"logrotate правила",
"docker overlay",
"docker swarm",
"kubernetes cni",
"kubernetes ingress",
"helm chart",
"etcd backup",
"kubeadm reset",
"kind cluster",
"podman rootless",
"lxc контейнеры",
"lxd snapshot",
"qemu kvm сеть",
"qemu passthrough",
"libvirt xml",
"virtio драйвер",
"proxmox backup",
"proxmox firewall",
"openstack nova",
"openstack neutron",
"xen scheduler",
"hypervisor сравнение",
"linux namespaces",
"ebpf hook",
"bcc tools",
"perf top",
"ftrace пример",
"strace вывод",
"gdb attach",
"core dump анализ",
"valgrind memcheck",
"asan ошибки",
"ubsan отчет",
"clang sanitizers",
"makefile pattern",
"cmake linking",
"ninja build",
"git rebase конфликт",
"git subtree",
"git-lfs пример",
"svn миграция",
"mercurial basics",
"ansible vault",
"ansible jinja",
"terraform state",
"packer образ",
"saltstack pillar",
"chef cookbook",
"puppet manifest",
"devops pipeline",
"jenkinsfile пример",
"gitlab ci yaml",
"github actions cache",
"cicd деплой",
"monitoring linux",
"sysstat iostat",
"htop фильтры",
"iotop мониторинг",
"nload график",
"iftop трафик",
"netstat сравнение",
"ss сокеты",
"tcpdump фильтры",
"tshark decode",
"wireshark tls",
"ethernet mtu",
"tcp window",
"sctp протокол",
"quic обзор",
"http3 тест",
"tls renegotiation",
"openssl сертификат",
"openssl csr",
"gnutls ошибка",
"gpg ключи",
"yubikey linux",
"fido2 ключ",
"pam_u2f пример",
"usb passthrough kvm",
"udevadm monitor",
"pci устройства",
"acpi таблицы",
"bios modding",
"uefi variables",
"secure boot linux",
"coreboot прошивка",
"tianocore edk2",
"ipmi управление",
"redfish api",
"idrac настройки",
"ilo консоль",
"bmc openbmc",
"raid hba прошивка",
"zfs send receive",
"btrfs balance",
"mdadm assemble",
"luks2 ключи",
"tpm2 tools",
"fips режим",
"linux hardening",
"kernel config",
"kernel build",
"kernel sysctl",
"sysctl net tuning",
"oom killer лог",
"nice приоритеты",
"cgroups cpu ограничение",
"numa балансировка",
"hugepages настройка",
"kvm nested",
"virtiofs performance",
"fancontrol pwm",
"lm-sensors detect",
"acpid правила",
"powertop оптимизация",
"cpupower governor",
"nvidia prime",
"optimus linux",
"steam proton",
"wine staging",
"vulkan драйвер",
"mesa gallium",
"flatpak sandbox",
"firejail профили",
"bubblewrap linux",
"snap confinement",
"rpm сборка",
"deb пакет",
"dpkg зависимость",
"apt pinning",
"yum dnf config",
"pacman hooks",
"arch mkinitcpio",
"gentoo emerge",
"nixos flakes",
"void linux runit",
"openbsd firewall",
"freebsd pf anchor",
"freebsd poudriere",
"freebsd jails",
"dragonflybsd hammer",
"netbsd pkgsrc",
"illumOS zones",
"solaris smf",
"aix tuning",
"hpux управление",
"openwrt firewall",
"opnsense proxy",
"vyos конфигурация",
"mikrotik ospf",
"juniper junos cli",
"cisco bgp настройка",
"arista eos",
"brocade vdx",
"ubnt unifi ssh",
"pfsense squid",
"radius mikrotik",
"mpls ldp cisco",
"ipv6 dhcpv6",
"ipv6 forwarding",
"dns64 nat64",
"wireguard roam",
"tor hidden service",
"i2p настройка",
"crowdsec firewall",
"osquery linux",
"rkhunter проверка",
"clamav настройка",
"yara правила",
"suricata sig",
"snort правила",
"zeek logs",
"maltrail сенсор",
"openvas сканирование",
"nessus агент",
"nmap скрипты",
"masscan скорость",
"hydra brute",
"hashcat режим",
"john пароль",
"2fa сервер",
"ldap авторизация",
"sso openid",
"oauth прокси",
"saml интеграция",
"vpn split tunneling",
"openconnect linux",
"fortigate sslvpn",
"panos cli",
"azure ad sync",
"aws iam",
"gcp cloud dns",
"digitalocean firewall",
"hetzner cloud init",
"terraform providers",
"ansible galaxy",
"k8s affinity",
"k8s tolerations",
"k8s storageclass",
"k8s crd пример",
"rook ceph",
"longhorn storage",
"harbor registry",
"trivy scanner",
"sonarqube анализ",
"promtail конфиг",
"loki запросы",
"tempo tracing",
"jaeger sampling",
"opentelemetry collector",
"istio ingress",
"linkerd sidecar",
"cilium ebpf",
"metallb config",
"ingress nginx tls",
"haproxy healthcheck",
"keepalived vip",
"corosync pacemaker",
"drbd sync",
"nodered flow",
"mosquitto mqtt",
"homeassistant linux",
"zigbee2mqtt usb",
"esp32 прошивка",
"stm32 toolchain",
"avr gcc",
"openocd конфиг",
"jtag отладка",
"yocto build",
"buildroot образ",
"raspberry gpio",
"raspberry pxe boot",
"orange pi uboot",
"rockchip драйвер",
"rk3399 linux",
"arm trusted firmware",
"riscv linux",
"qemu riscv",
"qemu arm64",
"kvm arm",
"gvisor container",
"wasm server",
"wasmtime пример",
"firecracker microvm",
"unikernel linux",
"bpftrace скрипты",
"ebpf socket filter"]

    all_results = {}
    excel_rows = []

    for q in queries:
        hits = search(q, size=10)
        all_results[q] = hits

        for hit in hits:
            excel_rows.append({
                "relevance": None,
                "query": q,
                "id": hit["id"],
                "keywords": ", ".join(hit["keywords"]),
                "title": hit["title"],
                "content": hit["content"]
            })

    with open("serp_results_5000.json", "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)

    df = pd.DataFrame(excel_rows)
    df.to_excel("serp_results_5000.xlsx", index=False)

    print("Готово: serp_results_5000.json и serp_results_5000.xlsx.")
